x-announce-env: &announce-env
  CLUSTER_ANNOUNCE_IP: ${CLUSTER_ANNOUNCE_IP:-127.0.0.1}

services:
  redis-1:
    image: redis:7.2-alpine
    restart: unless-stopped
    command: sh /usr/local/bin/redis-entrypoint.sh
    environment:
      <<: *announce-env
    volumes:
      - ./redis-1.conf:/usr/local/etc/redis/redis.conf
      - ./redis-entrypoint.sh:/usr/local/bin/redis-entrypoint.sh
      - ./redis-1-data:/data
    ports:
      - "6379:6379"
      - "16379:16379"
    networks:
      - redis-cluster-net

  redis-2:
    image: redis:7.2-alpine
    restart: unless-stopped
    command: sh /usr/local/bin/redis-entrypoint.sh
    environment:
      <<: *announce-env
    volumes:
      - ./redis-2.conf:/usr/local/etc/redis/redis.conf
      - ./redis-entrypoint.sh:/usr/local/bin/redis-entrypoint.sh
      - ./redis-2-data:/data
    ports:
      - "6380:6380"
      - "16380:16380"
    networks:
      - redis-cluster-net

  redis-3:
    image: redis:7.2-alpine
    restart: unless-stopped
    command: sh /usr/local/bin/redis-entrypoint.sh
    environment:
      <<: *announce-env
    volumes:
      - ./redis-3.conf:/usr/local/etc/redis/redis.conf
      - ./redis-entrypoint.sh:/usr/local/bin/redis-entrypoint.sh
      - ./redis-3-data:/data
    ports:
      - "6381:6381"
      - "16381:16381"
    networks:
      - redis-cluster-net

  redis-cluster-init:
    image: redis:7.2-alpine
    depends_on:
      - redis-1
      - redis-2
      - redis-3
    environment:
      <<: *announce-env
    volumes:
      - ./cluster-init.sh:/cluster-init.sh
    entrypoint: sh /cluster-init.sh
    networks:
      - redis-cluster-net

volumes:
  redis-1-data:
  redis-2-data:
  redis-3-data:

networks:
  redis-cluster-net:
    driver: bridge
