# redis-2.conf
port 6380
requirepass password
cluster-enabled yes
cluster-config-file nodes-2.conf
cluster-node-timeout 5000
appendonly yes
bind 0.0.0.0
protected-mode no
cluster-announce-ip 127.0.0.1
cluster-announce-port 6380
cluster-announce-bus-port 16380
