# redis-3.conf
port 6381
requirepass password
cluster-enabled yes
cluster-config-file nodes-3.conf
cluster-node-timeout 5000
appendonly yes
bind 0.0.0.0
protected-mode no
cluster-announce-ip 127.0.0.1
cluster-announce-port 6381
cluster-announce-bus-port 16381
