version: "3.8"
services:
  logstash_engine:
    ports:
      - 5000:5000
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ${HOME}/logstash:/logstash
    extra_hosts:
      - "localmachine:192.168.1.11"
  

networks:
  internal:
    driver: bridge