version: '3'
services:
  database:
    image: "postgres" # use latest official postgres version
    container_name: postgresql_server
    ports:
      - 5432:5432
    env_file:
      - database.env # configure postgres
    volumes:
      - postgresql-data:/var/lib/postgresql/data/ # persist data even if container shuts down
volumes:
  postgresql-data: # named volumes can be managed easier using docker-compose