version: '3'
services:
  rabbitmq:
    image: rabbitmq:3-management-alpine
    container_name: rabbitmq
    ports:
      - 5672:5672
      - 15672:15672
    volumes:
      - ./.docker/rabbitmq/etc/:/etc/rabbitmq/
      - ./.docker/rabbitmq/data/:/var/lib/rabbitmq/
      - ./.docker/rabbitmq/logs/:/var/log/rabbitmq/
  environment:
    RABBITMQ_ERLANG_COOKIE: 6085e2412b6fa88647466c6a81c0cea0
    RABBITMQ_DEFAULT_USER: user
    RABBITMQ_DEFAULT_PASS: password
    RABBITMQ_DEFAULT_VHOST: /