version: "3.7"
services:
  mysql:
    container_name: mysql
    image: mysql:8
    environment:
      - MYSQL_DATABASE=employee
      - MYSQL_USER=user
      - MYSQL_PASSWORD=password
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_ROOT_HOST=%
    ports:
      - "3306:3306"
    restart: always