services:
  mysql-5:
    platform: linux/x86_64
    container_name: mysql-5
    image: mysql:5.7.44
    ports:
      - "3306:3306"
    restart: always
    volumes:
      - ./data:/var/lib/mysql
    environment:
      - MYSQL_DATABASE=sinarelektronik
      - MYSQL_USER=user
      - MYSQL_PASSWORD=password
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_ROOT_HOST=%

