version: '3'
services:
  redis:
    image: redis:latest
    container_name: redis_server
    ports:
      - 6379:6379
    volumes:
      - ./config/redis.conf:/redis.conf
    command: [ "redis-server", "/redis.conf" ]