version: '3'
services:
  redis:
    image: redis:latest
    container_name: redis_latest
    ports:
      - 6379:6379
    volumes:
      - redis-data:/data
    command: [ "redis-server", "--appendonly", "yes" ]
volumes:
  redis-data: